#! /usr/bin/env bash

source set_env.sh
if [ $? != 0 ]; then
  exit 1
fi

sudo add-apt-repository -y ppa:libreoffice/ppa
sudo apt update
sudo apt install -y libreoffice
sudo apt install -y python3.9-venv
sudo apt install -y doxygen
sudo apt install -y graphviz

$pyexe -m ensurepip
rm -rf venv
$pyexe -m venv ./venv
source $pybin/activate

$pyexe -m pip install --upgrade pip
$pyexe -m pip install wheel
$pyexe -m pip install -r requirements.txt

# should be 3.9.0
$pyexe --version

deactivate
