#! /usr/bin/env bash

source set_env.sh
if [ $? != 0 ]; then
  exit 1
fi

brew install virtualenv
brew install doxygen
brew install graphviz
brew install basictex
brew install texlive
brew install --cask libreoffice

rm -rf venv
$pyexe -m venv ./venv
source $pybin/activate

$pyexe -m pip install --upgrade pip
$pyexe -m pip install wheel
$pyexe -m pip install -r requirements.txt

# should be 3.9.15
$pyexe --version

deactivate
