#! /bin/bash

source set_common.sh
tag='do_lint'

cmn_main_setup

cmn_log_start 'running pycodestyle'
pycodestyle | tee -a $OUTFILE
cmn_check_rc 'pycodestyle'

cmn_log_start 'running pylint'
pylint --rcfile=./pylint.rc *.py ${cmn_mod_name} | cmn_tee
cmn_check_rc 'pylint'

cmn_log_overall 'do_lint'
exit "${OVERALLRC}"
