#! /bin/bash

source set_common.sh

# --------------------
function logit() {
  tag=$1
  rc=$2
  if [ $rc = 0 ]; then
    printf "%-4s %s\n" "OK" "$tag RC=$rc"
  else
    printf "%-4s %s\n" "ERR" "$tag RC=$rc"
  fi
}

# --------------------
function main_setup() {
  cmn_activate_env
  cmn_clean_publish

  export PYTHONPATH=${PYTHONPATH}:.
}

# --------------------
function main_term() {
  deactivate
}

# --------------------
function check_rc() {
  RC=$?
  OVERALLRC=$((OVERALLRC + RC))
  logit "$1" $RC
}

## --------------------
# Note: currently unused
#function do_publish() {
#  $pyexe tools/publish/publish.py
#  check_rc 'run publish'
#}

# --------------------
function do_setup() {
  $pyexe setup.py -q sdist
  check_rc 'run setup'

  # check it
  twine check dist/*
  check_rc 'twine check'

  # upload it
  twine upload dist/*
  check_rc 'twine upload'
}

# --------------------
# ---- Main
main_setup
# do_publish # currently unused
if [ $OVERALLRC = 0 ]; then
  do_setup
fi
main_term

echo "     do_publish overall rc $OVERALLRC"
exit "${OVERALLRC}"
