#! /bin/bash

source set_common.sh

# --------------------
# run setup
# Note: currently unused
function pip_setup() {
  # install latest common modules
  ./do_update
}

# --------------------
# run the unit tests for named modules
function run_verification() {
  cmn_log_start 'run verification tests'

  cmn_set_coverage_opts
  pytest ${COV_SRC} ${COV_OPTS} ${modules} $@ | cmn_tee
  cmn_check_rc ${tag}
}

# --------------------
# run report
function run_report() {
  cmn_log_start 'run report'
  # no coverage
  $pyexe ver/gen_report.py | cmn_tee
  cmn_check_rc 'report'
}

# --------------------
# ---- Main
tag=ver

modules=""
modules+="ver/test_tp001.py "
modules+="ver/test_tp002.py "
modules+="ver/test_tp003.py "
modules+="ver/test_tp004.py "
modules+="ver/test_tp005.py "
modules+="ver/test_tp006.py "
modules+="ver/test_tp007.py "
modules+="ver/test_tp008.py "

COV_SRC="--cov=$cmn_mod_name/lib"

# run tests
cmn_main_setup
cmn_run_setup
run_verification $@
run_report
cmn_run_coverage

cmn_log_overall 'do_ver'
exit "${OVERALLRC}"
