#! /bin/bash

source set_common.sh

# --------------------
# run the simulated pump
function run_it() {
  $pyexe sample/main.py
  cmn_check_rc 'sim device'
}

# --------------------
# ---- Main
tag='doit'
cmn_main_setup
cmn_run_setup
run_it

cmn_log_overall 'doit'
exit "${OVERALLRC}"
